# Where things are
destination         : ./_site
# collections_dir     : .
# plugins_dir         : []
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Handling Reading
include             : []
exclude             : []
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "md"
strict_front_matter : true

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []
remote_theme        : Jekyll-Garden/jekyll-garden.github.io

# Conversion
markdown            : kramdown
excerpt_separator   : "\n\n"

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : Europe/Paris

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Gist Processors
#! gist:
#!   noscript: false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  #! math_engine: mathjax
  #! syntax_highlighter: rouge
