# version: '3.9'

# services:
#   web:
#     build:
#       context: app
#     # flask requires SIGINT to stop gracefully
#     # (default stop signal from Compose is SIGTERM)
#     stop_signal: SIGINT
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./app:/app
#     environment:
#       FLASK_ENV: development
version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
      - FLAG=REDACTED
    command: bash /code/wrapper-entrypoint.sh