services:
  chall:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./flag.txt:/flag/randomflaglolilolbigbisous.txt
      - /tmp # required for build & temp dirs
    restart: unless-stopped
    read_only: true
